### ISSUE TITLE
Patch for /trunk/libGpx4J/src/org/casaca/gpx4j/core/driver/jaxb/JaxbAdapter.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [greenflash1986/gpx4j#15]
```
JaxbAdapter.fromWaypoint does not copy the Waypoints lat/lng values into the 
WptType, this results in the written XML to not have any lat/lng values.
```

Original issue reported on code.google.com by `will.qu...@gmail.com` on 7 Jan 2015 at 4:17

Attachments:
- [JaxbAdapter.java.patch](https://storage.googleapis.com/google-code-attachments/gpx4j/issue-15/comment-0/JaxbAdapter.java.patch)

**Comment by greenflash1986** [comment]
patch applied
